# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 934d154c469e0f2daba03e0daeb2e183fdb1a2dba15e0ec4c62f611219eaa4233f7b6a9215894f42830e6fe1e0101508cd97d5c85920932f10378b4445ec4e46

test:
  secret_key_base: d468d9786dc1ec62e45ddbd78bbed84f257ce9080bf61a8ae1db3010eaabf6c604271c49c4e7e1155aff9a2feecf3b73cfa92c966b7e1c5234b7a20bc809227b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
